### ISSUE TITLE
Duplicate properties neither of which work! 

### ISSUE THREAD

**Issue by abdullahseba** [SSilence/php-imap-client#144]
Hi again 
There is a  `header.seen` and  `header.details.Unseen`.
Both don't seem to do anything, I marked a message as unread and `header.seen` had `1` and `header.details.Unseen` was still empty. Same if I send a new message.
```
 {
        "header": {
            "subject": "testo",
            "from": "Abdullah Seba <abdullah.seba@outlook.com>",
            "to": "E17 Pumphouse shop <admin@e17pumphouse.org.uk>",
            "date": "Thu, 20 Apr 2017 00:04:26 +0000",
            "message_id": "<VI1PR09MB04484911F122A2B60CC3DCB5FC1B0@VI1PR09MB0448.eurprd09.prod.outlook.com>",
            "size": 48087,
            "uid": 220,
            "msgno": 17,
            "recent": 0,
            "flagged": 0,
            "answered": 0,
            "deleted": 0,
            "seen": 1,  //<<<<<<<<<<<------------------ this one
            "draft": 0,
            "udate": 1492646668,
            "details": {
                "date": "Thu, 20 Apr 2017 00:04:26 +0000",
                "Date": "Thu, 20 Apr 2017 00:04:26 +0000",
                "subject": "testo",
                "Subject": "testo",
                "message_id": "<VI1PR09MB04484911F122A2B60CC3DCB5FC1B0@VI1PR09MB0448.eurprd09.prod.outlook.com>",
                "toaddress": "E17 Pumphouse shop <admin@e17pumphouse.org.uk>",
                "to": [
                    {
                        "personal": "E17 Pumphouse shop",
                        "mailbox": "admin",
                        "host": "e17pumphouse.org.uk"
                    }
                ],
                "fromaddress": "Abdullah Seba <abdullah.seba@outlook.com>",
                "from": [
                    {
                        "personal": "Abdullah Seba",
                        "mailbox": "abdullah.seba",
                        "host": "outlook.com"
                    }
                ],
                "Recent": " ",
                "Unseen": " ", //<<<<<<<<<<<------------------ and this one
                "Flagged": " ",
                "Answered": " ",
                "Deleted": " ",
                "Draft": " ",
                "Msgno": "  17",
                "MailDate": "20-Apr-2017 01:04:28 +0100",
                "Size": "48087",
                "udate": 1492646668
            }

**Comment by abdullahseba** [comment]
Might be office 365 cuz when I refresh office it sometimes un does what I did.
Have to look into it
Still the duplicate tho.

**Comment by abdullahseba** [comment]
![image](https://cloud.githubusercontent.com/assets/25548754/25218967/9da27b64-25a4-11e7-86b3-779c8ba29e6c.png)

**Comment by abdullahseba** [comment]
![image](https://cloud.githubusercontent.com/assets/25548754/25219010/ca3c5f1e-25a4-11e7-85e0-c5554e70291e.png)

**Comment by sergey144010** [comment]
Ok.
Questions:
1. You first had 1 unread message. You have web interface and in it you see that the letter is not read?

2. You took it with getMessage(). And looked
```php
$imap->inMess->header
```
Yes or No ?

3. The letter became read?
Yes or No ?

4. Do you want to set it as not read?

5. To do this, you use $imap->setUnseenMessage() method?

6. You open the interface and the letter is read again?

P.S. When using getMessage() method, the letter is marked as read.

**Comment by sergey144010** [comment]
And 'details' property
```php
$imap->inMess->header->details
```
Just uses it
```php
imap_headerinfo($this->imapStream, $this->id);
```
This is a Php built-in function.
See http://php.net/manual/ru/function.imap-headerinfo.php
```php
Unseen - U if not seen AND not recent, ' ' if seen OR not seen and recent 
```

**Comment by sergey144010** [comment]
When I use the web interface and use $imap->setUnseenMessage() method, the update in the web interface does not happen instantly, it is necessary to switch between folders, and then an unread message will appear.

**Comment by abdullahseba** [comment]
I have not got to the bit that reads mail in the interface yet. All I'm doing is `$imap->getMessages()`
I Think its a problem with office Ui
I'll check with Gmail and let you know. 
What about `header.details.Unseen`?

**Comment by abdullahseba** [comment]
Cant get anything out of gmail....

**Comment by abdullahseba** [comment]
`$emails = $imap->getMessages();`
returns this in gmail:
`Notice: Unknown: Invalid quoted-printable sequence: =n&p=inboxcategories_all> [image: Customize] Customize your inbox If you see (errflg=3) in Unknown on line 0`

works fin in office 365!

**Comment by sergey144010** [comment]
What this?
```php
inboxcategories_all
```
Do you use it?
```php
$imap = new ImapClient([
    ...
    'mailbox' => [
        'remote_system_name' => 'imap.server.ru',
        'mailbox_name' => INBOX.categories,
    ],
...
]);
```
or
```php
$imap = new ImapClient([
    ...
    'mailbox' => [
        'remote_system_name' => 'imap.server.ru',
        'mailbox_name' => INBOX/categories,
    ],
...
]);
```

**Comment by abdullahseba** [comment]
No, I don't. Its just ` $imap->getMessages()` exact same code that works with 365 but returns this.

**Comment by sergey144010** [comment]
try this
```php
$imap = new ImapClient([
    ...
    'mailbox' => [
        'remote_system_name' => 'imap.server.ru',
        'mailbox_name' => INBOX,
    ],
...
]);
$imap->selectFolder(categories);
$emails = $imap->getMessages();
```

**Comment by abdullahseba** [comment]
why?
isn't that the advanced connection?

**Comment by sergey144010** [comment]
That is.
You do not have a folder separator here.
```php
inboxcategories_all
```

**Comment by xXXIMMATTHEWXXx** [comment]
I believe your issue is not connecting to the default folder @abdullahseba. As @sergey144010 said, try and use the default then switch.

**Comment by xXXIMMATTHEWXXx** [comment]
Do note @abdullahseba that an advanced connection is _highly_ recommended.

**Comment by JerBlo** [comment]
I can reproduce this issue and debugged this issue. When using ImapClient::getMessages, each message is retrieved by the getMessage() function, which lead to IncomingMessage::init().

In this function, the getHeader() method is called AFTER getAttachments (which marks the e-mail as read/seen). In my opinion the getHeader() should be right before the getAttachments.

**Comment by abdullahseba** [comment]
Yep its defiantly not outlook now. As soon as I refresh the client my emails get read.

**Comment by xXXIMMATTHEWXXx** [comment]
@JerBlo's solution seems to be the most logical.

**Comment by abdullahseba** [comment]
Thats something you have to do right?

**Comment by xXXIMMATTHEWXXx** [comment]
Yes, I will commit in a minute.

**Comment by xXXIMMATTHEWXXx** [comment]
I believe this has been fixed. Let me know

**Comment by abdullahseba** [comment]
Yep seems to work. but the time is always 20 hours.
Might be me but the code use to work.

**Comment by abdullahseba** [comment]
![image](https://cloud.githubusercontent.com/assets/25548754/25384490/64bc1608-29b8-11e7-940a-af23b01c2dda.png)

**Comment by abdullahseba** [comment]
Cant cuz of the attachment issue #153.
I can `$emails = $imap->getMessages(10,1);`
I was using `header.udate`

**Comment by xXXIMMATTHEWXXx** [comment]
Try and send yourself a new one

**Comment by abdullahseba** [comment]
No its ok must be my js somewhere.
the duplicate headers are still there tho
```
"header": {
            "subject": "Receipt for your PayPal payment to Bamford Trading (UK) Ltd",
            "from": "\"service@paypal.co.uk\" <service@paypal.co.uk>",
            "to": "Peter Spence <admin@e17pumphouse.org.uk>",
            "date": "Mon, 17 Apr 2017 10:39:37 +0000",
            "message_id": "<1492425577.32417@paypal.com>",
            "size": 63770,
            "uid": 177,
            "msgno": 14,
            "recent": 0,
            "flagged": 1,
            "answered": 0,
            "deleted": 0,
            "seen": 1,
            "draft": 0,
            "udate": 1492425583,
            "details": {
                "date": "Mon, 17 Apr 2017 10:39:37 +0000",
                "Date": "Mon, 17 Apr 2017 10:39:37 +0000",
                "subject": "Receipt for your PayPal payment to Bamford Trading (UK) Ltd",
                "Subject": "Receipt for your PayPal payment to Bamford Trading (UK) Ltd",
                "message_id": "<1492425577.32417@paypal.com>",
                "toaddress": "Peter Spence <admin@e17pumphouse.org.uk>",
                "to": [
                    {
                        "personal": "Peter Spence",
                        "mailbox": "admin",
                        "host": "e17pumphouse.org.uk"
                    }
                ],
                "fromaddress": "\"service@paypal.co.uk\" <service@paypal.co.uk>",
                "from": [
                    {
                        "personal": "service@paypal.co.uk",
                        "mailbox": "service",
                        "host": "paypal.co.uk"
                    }
                ],
                "Recent": " ",
                "Unseen": " ",
                "Flagged": "F",
                "Answered": " ",
                "Deleted": " ",
                "Draft": " ",
                "Msgno": "  14",
                "MailDate": "17-Apr-2017 11:39:43 +0100",
                "Size": "63770",
                "udate": 1492425583
            }

**Comment by abdullahseba** [comment]
No its not fixed.
I can see the mail getting marked as read in outlook as i refresh the page.
Fixed the date issue (was my JS).

**Comment by abdullahseba** [comment]
They come thorough as unread than when I refresh the page again its read.
I can send link if you want.

**Comment by xXXIMMATTHEWXXx** [comment]
Hm...

**Comment by sergey144010** [comment]
@JerBlo So
>  the getHeader() method is called AFTER getAttachments (which marks the e-mail as read/seen)
Because marks the e-mail as read/seen, getHeader() method MUST BE AFTER.
Otherwise it turns out that you take the header of the letter and there
```php
header->seen = 0
```
Then the letter is read by getAttachments() and getBody() method. And it establishes
```php
header->seen = 1
```
And when you receive a message, the header is not correct, the letter has already been read, but you have not read it.

**Comment by sergey144010** [comment]
And so if you have already fixed it, then I recommend that you return it back, because it breaks the logic.

**Comment by xXXIMMATTHEWXXx** [comment]
Reopened due to new convo

**Comment by sergey144010** [comment]
I say it again.
When using the methods of getMessage() and getMessages(), the mail is marked as read, because it is logged into the logic. If you want to get only message headers then use the `$imap-> getMessagesOverview ()` method with the parameters `$imap->getMessagesOverview ('1:20')` where `1: 20` is the id range that you can do so
```php
$count = $imap->countMessages();
$string = '1:'.$count;
$emails = $imap->getMessagesOverview ($string);
# and next
foreach($emails as $email){
#... for example
print $email->from;
}
```

**Comment by abdullahseba** [comment]
returns nothing

**Comment by abdullahseba** [comment]
Thats nearly perfect but I need to know if it has attachments and `'1:20'` is a HUGE downside for me.
Is there a way to get the _last 20 emails_?

**Comment by sergey144010** [comment]
If I'm not mistaking, the mail server on receiving a new message, he shifts the id, and the uid leaves unchanged. Accordingly, this will be the last 20 messages.
```php
$imap->getMessagesOverview ('1:20');
```
And find out if there is an attachments or not, so long as except `$map->getMessage($id); $imap->IncomingMessage->attachments` can not.

**Comment by abdullahseba** [comment]
no it starts from the bottem up so i get my first 20 emails

**Comment by sergey144010** [comment]
So you need to calculate the last.
```php
$count = $map->countMessages();
$start = $count-20;
$string = $start.':'.$count;
$imap->getMessagesOverview ($string);
```

**Comment by sergey144010** [comment]
And maybe you need to turn them over so
```php
$count = $map->countMessages();
$start = $count-20;
$string = $start.':'.$count;
$emails = $imap->getMessagesOverview ($string);
$emails = array_reverse($emails);
```

**Comment by abdullahseba** [comment]
Last  one works :)

**Comment by abdullahseba** [comment]
`$imap->selectFolder();` does not work for this. any alternative?

**Comment by sergey144010** [comment]
And why does it work for me?
```php
    $imap->selectFolder('INBOX/Folder1');
    $count = $imap->countMessages();
    var_dump($count);
    $imap->selectFolder('INBOX/Folder2');
    $count = $imap->countMessages();
    var_dump($count);
    $imap->selectFolder('INBOX/Folder3');
    $count = $imap->countMessages();
    var_dump($count);
```
return
```php
int(83)
int(9)
int(2335)
```

**Comment by abdullahseba** [comment]
No, `$imap->countMessages();` works but `$imap->getMessagesOverview` does not work unless INBOX is selected. it just reruns an empty array and an error
```
[]
Notice: Unknown: Syntax error in sequence (errflg=2) in Unknown on line 0

**Comment by sergey144010** [comment]
I have
```php
    $imap->selectFolder('INBOX/Folder1);
    $count = $imap->countMessages();
    var_dump($count);
    $br = count($imap->getBriefInfoMessages());
    var_dump($br);

    $imap->selectFolder('INBOX/Folder2');
    $count = $imap->countMessages();
    var_dump($count);
    $br = count($imap->getBriefInfoMessages());
    var_dump($br);

    $imap->selectFolder('INBOX/Folder3');
    $count = $imap->countMessages();
    var_dump($count);
    $br = count($imap->getBriefInfoMessages());
    var_dump($br);
```
return
```php
int(83)
int(83)
int(9)
int(9)
int(2335)
int(2335)
```

**Comment by abdullahseba** [comment]
`int(1) int(1)`

**Comment by abdullahseba** [comment]
I neeed `$imap->getMessagesOverview` not `$imap->getBriefInfoMessages`!!!!

**Comment by abdullahseba** [comment]
```
$imap->selectFolder('Junk Email');
$count = $imap->countMessages();
$start = $count-20;
$string = $start.':'.$count;
$emails = $imap->getMessagesOverview ($string);
$emails = array_reverse($emails);

**Comment by abdullahseba** [comment]
```
$folders = $imap->getFolders();
   foreach($folders as $folder => $subFolder) {
    print_r ($folder.PHP_EOL);  
}
```
Returns `Calendar Calendar/Birthdays Calendar/United Kingdom holidays Contacts Conversation History Deleted Items Drafts INBOX Journal Junk Email Notes Outbox Sent Items Tasks`
And
```
$imap->selectFolder('Junk Email');
print_r($imap->getMessages());
```
works so why not `$imap->getMessagesOverview()`?

**Comment by sergey144010** [comment]
show you
```php
var_dump($imap->getFolders(null, 1));
```

**Comment by abdullahseba** [comment]
```
array(14) { [0]=> string(8) "Calendar" [1]=> string(18) "Calendar/Birthdays" [2]=> string(32) "Calendar/United Kingdom holidays" [3]=> string(8) "Contacts" [4]=> string(20) "Conversation History" [5]=> string(13) "Deleted Items" [6]=> string(6) "Drafts" [7]=> string(5) "INBOX" [8]=> string(7) "Journal" [9]=> string(10) "Junk Email" [10]=> string(5) "Notes" [11]=> string(6) "Outbox" [12]=> string(10) "Sent Items" [13]=> string(5) "Tasks" }

**Comment by sergey144010** [comment]
Show you
```php
    $imap->selectFolder('Calendar/Birthdays');
    $count = $imap->countMessages();
    var_dump($count);
    $br = count($imap->getMessagesOverview());
    var_dump($br);

    $imap->selectFolder('Junk Email');
    $count = $imap->countMessages();
    var_dump($count);
    $br = count($imap->getMessagesOverview());
    var_dump($br);
```

**Comment by abdullahseba** [comment]
`Calendar/Birthdays` is an outlook thing not a mailbox. Its for the office calander and not even shown in outlook.
```
int(0) 
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SSilence\ImapClient\ImapClient::getMessagesOverview(), 0 passed in C:\xampp\htdocs\mail2\1.php on line 30 and at least 1 expected in C:\xampp\htdocs\mail2\vendor\ssilence\php-imap-client\ImapClient\ImapClient.php:986 Stack trace: #0 C:\xampp\htdocs\mail2\1.php(30): SSilence\ImapClient\ImapClient->getMessagesOverview() #1 {main} thrown in C:\xampp\htdocs\mail2\vendor\ssilence\php-imap-client\ImapClient\ImapClient.php on line 986

**Comment by abdullahseba** [comment]
```
int(0) 
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SSilence\ImapClient\ImapClient::getMessagesOverview(), 0 passed in C:\xampp\htdocs\mail2\1.php on line 30 and at least 1 expected in C:\xampp\htdocs\mail2\vendor\ssilence\php-imap-client\ImapClient\ImapClient.php:986 Stack trace: #0 C:\xampp\htdocs\mail2\1.php(30): SSilence\ImapClient\ImapClient->getMessagesOverview() #1 {main} thrown in C:\xampp\htdocs\mail2\vendor\ssilence\php-imap-client\ImapClient\ImapClient.php on line 986

**Comment by xXXIMMATTHEWXXx** [comment]
@abdullahseba the getMessagesOverview depends on the mailbox connection to read the emails. Are you switching your open folder? getMessagesOverview also depends on an id: `@param string $sequence a message sequence description,
     * you can enumerate desired messages with the X,Y syntax,
     * or retrieve all messages within an interval with the X:Y syntax`

**Comment by xXXIMMATTHEWXXx** [comment]
@abdullahseba is this still an issue?

**Comment by abdullahseba** [comment]
I dont know I haven't upgraded for sometime, but have you fixed it?

**Comment by xXXIMMATTHEWXXx** [comment]
I believe we have. Can you test it? If you dont want your code to break make it in a new environment please.

**Comment by abdullahseba** [comment]
Ok I will try later on hopefully today, not worried about the code. its easy to downgrade with composer.

**Comment by abdullahseba** [comment]
Right I seems to work but its still duplicated.
The second lot should should say `0` instead of been blank tho.
If this is the intended behaviour I'll  close the issue. 
![image](https://cloud.githubusercontent.com/assets/25548754/25900808/9b3a81a8-358c-11e7-969b-52c77814b8c2.png)

**Comment by xXXIMMATTHEWXXx** [comment]
Everything looks good but the date. Will fix this

**Comment by abdullahseba** [comment]
Yeah, that is duplicated too in the same place.

**Comment by xXXIMMATTHEWXXx** [comment]
Seems to be just a human error ;)

**Comment by abdullahseba** [comment]
Shall I open another issue for the messages getting marked as read? 
We spoke about it here but its confusing.

**Comment by xXXIMMATTHEWXXx** [comment]
Yes please

**Comment by xXXIMMATTHEWXXx** [comment]
@abdullahseba did you ever orr?
